---
- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: Restart postfix

- name: Add sasl credentials
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl/sasl_passwd
    mode: '0400'
  register: _sasl
  when: postfix_sasl_credentials is defined

- name: Create hashmap db for SMTP relay credentials
  command: postmap hash:/etc/postfix/sasl/sasl_passwd
  when:
    - postfix_sasl_credentials is defined
    - _sasl.changed

- name: Make hashmap db read only
  file:
    path: /etc/postfix/sasl/sasl_passwd.db
    mode: '0400'
  when: postfix_sasl_credentials is defined

- name: Disable SMTP listener
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: '^(smtp.+smtpd)$'
    line: '#\1'
    backrefs: yes
  when: not postfix_enable_smtp_listener
  notify: Restart postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: started
    enabled: True
